<?php
$this->headTitle('Change Password');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Users'=>$this->url('users'),
            'Change Password'=>$this->url('users', ['action'=>'change-password', 'id'=>$user->getId()])
            ]);

$form->get('old_password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Enter old password',
    'size'=>30
    ]);

$form->get('new_password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Enter new password',
    'size'=>30
    ]);

$form->get('confirm_new_password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Re-enter new password',
    'size'=>30
    ]);

$form->get('submit')->setAttributes(['class'=>'btn-primary',
    'style'=>'background-color: #1bbc9b;color:white;']);

$form->prepare();
?>
<div class="ts-page-title">

    <div class="custom" style="background-image: url(<?php echo $this->basePath().'/ressources/img/banner/banner5.jpg';?>)">
        <h2>MODIFICATION DE MOT DE PASSE</h2>
    </div>

</div>
<div id="t3-mainbody" class="container t3-mainbody">
	<div class="row">
            <!-- MAIN CONTENT -->
            <div id="t3-content" class="t3-content col-xs-12">
		<div id="system-message-container">
                </div>
                
		<div class="contact" itemscope itemtype="http://schema.org/Person">
                    <dl class="contact-address dl-horizontal" itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
	
                    </dl>
		
                    <span></span> <h3><?= $this->escapeHtml($user->getEmail()) ?></h3>
                    <div id="contact-form" class="contact-form">
                        <?= $this->form()->openTag($form); ?>
                            <fieldset>
                                <legend>Modifier le mot de passe d'un utilisateur de la plateforme de sécurisaton. Tous les champs avec un asterisk (*) sont obligatoires.</legend>
                                <div class="row">
                                    <div class="col-md-4">
					<div class="control-group">
                                            <label class="hasPopover required">
                                               <?= $this->formLabel($form->get('old_password')); ?><span class="star">&#160;*</span>
                                            </label>
                                            <?= $this->formElement($form->get('old_password')); ?>
                                            <?= $this->formElementErrors($form->get('old_password')); ?>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
					<div class="control-group">
                                            <label class="hasPopover required">
                                               <?= $this->formLabel($form->get('new_password')); ?><span class="star">&#160;*</span>
                                            </label>
                                            <?= $this->formElement($form->get('new_password')); ?>
                                            <?= $this->formElementErrors($form->get('new_password')); ?>					
                                        </div>
                                    </div>
                                    <div class="col-md-4">
					<div class="control-group">
                                            <label class="hasPopover required">
                                               <?= $this->formLabel($form->get('confirm_new_password')); ?><span class="star">&#160;*</span>
                                            </label>
                                            <?= $this->formElement($form->get('confirm_new_password')); ?>
                                            <?= $this->formElementErrors($form->get('confirm_new_password')); ?>					
                                        </div>
                                    </div>
                                </div>
                                
				<?= $this->formElement($form->get('csrf')); ?>
                                <?= $this->formElement($form->get('submit')); ?>
                            </fieldset>
                        <?= $this->form()->closeTag(); ?>
                    </div>
		</div>
            </div>
		<!-- //MAIN CONTENT -->
	</div>
</div>