<?php
$this->headTitle('Utilisateurs');

$this->mainMenu()->setActiveItemId('users');
$this->mainMenu()->setDataTableAssets(true);
$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Users'=>$this->url('users'),
            ]);
?>
    
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h4 class="mb-0 font-size-18">Liste des utilisateurs</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Liste des utilisateur</a></li>
                        <li class="breadcrumb-item active">Utilisateurs</li>
                    </ol>
                </div>

            </div>
        </div>
    </div>   
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <table id="user-datatable" width='100%' class="table dt-responsive nowrap">
                        <thead>
                            <tr>
                                <th>Nom & Prénoms</th>
                                <th>E-mail</th>
                                <th>Rôle(s)</th>
                                <th>Statut</th>
                                <th colspan="3">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->users as $user): ?>
                            <tr>
                                <td>
                                    <?= $user->getNom() .' '.$user->getPrenoms()?>
                                </td>
                                <td>
                                    <?= $this->escapeHtml($user->getEmail()); ?>
                                </td>
                                <td>
                                    <?= $this->escapeHtml($user->getRolesAsString()); ?></a> 
                                </td>       
                                <td><?= $this->escapeHtml($user->getStatusAsString()); ?></td>
                                <td colspan="1">
                                    <a class="btn btn-sm btn-info" href="<?= $this->url('users', ['action'=>'voir-details', 'id'=>$user->getUserId()]); ?>">
                                        Voir
                                    </a>
                                </td>
                                <td colspan="1">
                                    <a class="btn btn-sm btn-success" href="<?= $this->url('users', ['action'=>'edit', 'id'=>$user->getUserId()]); ?>">
                                        Editer
                                    </a>
                                </td>
                                <td colspan="1">
                                    <a class="btn btn-sm btn-danger" href="<?= $this->url('users', ['action'=>'voir-details', 'id'=>$user->getUserId()]); ?>">
                                        Supprimer
                                    </a>
                                </td>
                            </tr>
                            <?php endforeach; ?> 
                        </tbody>
                    </table>

                </div> <!-- end card body-->
            </div> <!-- end card -->
        </div><!-- end col-->
    </div>
    <!-- end row-->