<?php
$this->headTitle('Paramètres');

$this->mainMenu()->setActiveItemId('params');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home')
            ]);
?>


<div class="row">
    <div class="col-xl-12">
        <div class="row">
            <div class="col-lg-4">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title" style="color:#FF9800"><i class="feather-home"> </i>Spécialités</h4>
                        Dans cette partie, vous pouvez afficher la liste de toutes les spécialités
                        <div class="row align-items-left">
                            <div class="col-5 m-0">
                                <a href=""
                                    class="btn btn-outline-success mt-3 btn-rounded waves-effect waves-light">
                                    <i class="feather-folder"> Ouvrir</i>
                                </a>
                            </div>
                            <div class="col-5">
                                <a href=""
                                    class="btn btn-outline-success mt-3 btn-rounded waves-effect waves-light">
                                    <i class="feather-check-circle"> Nouveau</i>
                                </a>
                            </div>
                        </div> <!-- end row -->
                    </div> <!-- end card-body-->
                </div> <!-- end card-->
            </div> <!-- end col-->

            <div class="col-lg-4">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title" style="color:#FF9800"><i class="feather-home"> </i>Niveaux d'études</h4>
                        Dans cette partie, vous pouvez afficher la liste de tous les niveaux d'études
                        <div class="row align-items-left">
                            <div class="col-5 m-0" >
                                <a href=""
                                    class="btn btn-outline-success mt-3 btn-rounded waves-effect waves-light">
                                    <i class="feather-folder"> Ouvrir</i>
                                </a>
                            </div>
                            <div class="col-5">
                                <a href=""
                                    class="btn btn-outline-success mt-3 btn-rounded waves-effect waves-light">
                                    <i class="feather-check-circle"> Nouveau</i>
                                </a>
                            </div>
                        </div> <!-- end row -->
                    </div> <!-- end card-body-->
                </div> <!-- end card-->
            </div> <!-- end col-->

            <div class="col-lg-4">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title" style="color:#FF9800"><i class="feather-briefcase"> </i>Types de media</h4>
                        Dans cette partie, vous pouvez afficher la liste de tous les types de media
                        <div class="row align-items-left">
                            <div class="col-5 m-0" >
                                <a href=""
                                    class="btn btn-outline-success mt-3 btn-rounded waves-effect waves-light">
                                    <i class="feather-folder"> Ouvrir</i>
                                </a>
                            </div>
                            <div class="col-5">
                                <a href=""
                                    class="btn btn-outline-success mt-3 btn-rounded waves-effect waves-light">
                                    <i class="feather-check-circle"> Nouveau</i>
                                </a>
                            </div>
                        </div> <!-- end row -->
                    </div> <!-- end card-body-->
                </div> <!-- end card-->
            </div> <!-- end col-->
            
        </div>
        <!-- end row-->
	</div>
</div>


<div class="row">
    <div class="col-xl-12">
        <div class="row">
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title" style="color:#FF9800"><i class="feather-home"> </i>Types de formation</h4>
                        Dans cette partie, vous pouvez afficher la liste de tous les types de formation
                        <div class="row align-items-left">
                            <div class="col-5 m-0" >
                                <a href=""
                                    class="btn btn-outline-success mt-3 btn-rounded waves-effect waves-light">
                                    <i class="feather-folder"> Ouvrir</i>
                                </a>
                            </div>
                            <div class="col-5">
                                <a href=""
                                    class="btn btn-outline-success mt-3 btn-rounded waves-effect waves-light">
                                    <i class="feather-check-circle"> Nouveau</i>
                                </a>
                            </div>
                        </div> <!-- end row -->
                    </div> <!-- end card-body-->
                </div> <!-- end card-->
            </div> <!-- end col-->

            <div class="col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title" style="color:#FF9800"><i class="feather-briefcase"> </i>Types de media</h4>
                        Dans cette partie, vous pouvez afficher la liste de tous les types de media
                        <div class="row align-items-left">
                            <div class="col-5 m-0" >
                                <a href=""
                                    class="btn btn-outline-success mt-3 btn-rounded waves-effect waves-light">
                                    <i class="feather-folder"> Ouvrir</i>
                                </a>
                            </div>
                            <div class="col-5">
                                <a href=""
                                    class="btn btn-outline-success mt-3 btn-rounded waves-effect waves-light">
                                    <i class="feather-check-circle"> Nouveau</i>
                                </a>
                            </div>
                        </div> <!-- end row -->
                    </div> <!-- end card-body-->
                </div> <!-- end card-->
            </div> <!-- end col-->
		</div>
	</div>
</div>
<!-- end row-->


<div class="row">
    <div class="col-xl-12">
        <div class="row">
            <div class="col-lg-4">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title" style="color:#FF9800"><i class="feather-home"> </i>Pays</h4>
                        Dans cette partie, vous pouvez afficher la liste de tous les Pays
                        <div class="row align-items-left">
                            <div class="col-5 m-0">
                                <a href=""
                                    class="btn btn-outline-success mt-3 btn-rounded waves-effect waves-light">
                                    <i class="feather-folder"> Ouvrir</i>
                                </a>
                            </div>
                            <div class="col-5">
                                <a href=""
                                    class="btn btn-outline-success mt-3 btn-rounded waves-effect waves-light">
                                    <i class="feather-check-circle"> Nouveau</i>
                                </a>
                            </div>
                        </div> <!-- end row -->
                    </div> <!-- end card-body-->
                </div> <!-- end card-->
            </div> <!-- end col-->

            <div class="col-lg-4">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title" style="color:#FF9800"><i class="feather-home"> </i>Villes</h4>
                        Dans cette partie, vous pouvez afficher la liste de toutes les villes
                        <div class="row align-items-left">
                            <div class="col-5 m-0" >
                                <a href=""
                                    class="btn btn-outline-success mt-3 btn-rounded waves-effect waves-light">
                                    <i class="feather-folder"> Ouvrir</i>
                                </a>
                            </div>
                            <div class="col-5">
                                <a href=""
                                    class="btn btn-outline-success mt-3 btn-rounded waves-effect waves-light">
                                    <i class="feather-check-circle"> Nouveau</i>
                                </a>
                            </div>
                        </div> <!-- end row -->
                    </div> <!-- end card-body-->
                </div> <!-- end card-->
            </div> <!-- end col-->

            <div class="col-lg-4">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title" style="color:#FF9800"><i class="feather-briefcase"> </i>Communes</h4>
                        Dans cette partie, vous pouvez afficher la liste de toutes les communes
                        <div class="row align-items-left">
                            <div class="col-5 m-0" >
                                <a href=""
                                    class="btn btn-outline-success mt-3 btn-rounded waves-effect waves-light">
                                    <i class="feather-folder"> Ouvrir</i>
                                </a>
                            </div>
                            <div class="col-5">
                                <a href=""
                                    class="btn btn-outline-success mt-3 btn-rounded waves-effect waves-light">
                                    <i class="feather-check-circle"> Nouveau</i>
                                </a>
                            </div>
                        </div> <!-- end row -->
                    </div> <!-- end card-body-->
                </div> <!-- end card-->
            </div> <!-- end col-->
            
		</div>
		<!-- end row-->
	</div>
</div>