<?php
$this->headTitle('Ajouter une formation');

$this->mainMenu()->setActiveItemId('formation');

$this->pageBreadcrumbs()->setItems([
            'Accueil'=>$this->url('admin')
            ]);
////var_dump($form);die();
 $form->get('montant')->setAttributes([
    'class'=>'form-control', 
    
    ]);
 
 $form->get('remise')->setAttributes([
    'class'=>'form-control',
    
    ]);
 
 $form->get('niveau')->setAttributes([
    'class'=>'form-control', 
    
    ]);
 
 $form->get('specialite')->setAttributes([
    'class'=>'form-control',
    ]);
 
 $form->get('date')->setAttributes([
    'class'=>'form-control',
    'data-toggle'=>'select2', 
    ]);
 
 $form->get('enregistrer')->setAttributes([
    'class'=>'btn btn-sm btn-success waves-effect waves-light float-right',
    ]);
 $form->get('annuler')->setAttributes([
    'class'=>'btn btn-sm btn-danger waves-effect waves-light float-left',
    ]);
 
 
$form->prepare();

?>
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0 font-size-18">Ajout des conditions de participation à la formation </h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Détails de la formation</a></li>
                    <li class="breadcrumb-item active">conditions</li>
                </ol>
            </div>

        </div>
    </div>
    <div class="col-12">
            <?= $this->flashMessenger()->render('error', ['alert', 'alert-danger alert-dismissible fade show']); ?>
            <?= $this->flashMessenger()->render('success', ['alert', 'alert-success alert-dismissible fade show']); ?>
            <?= $this->flashMessenger()->render('info', ['alert', 'alert-info alert-dismissible fade show']); ?>
    </div>
</div>  
<div class="card">
    <div class="card-body" style="padding-top: 50px; padding-bottom: 50px;">
       
        <?= $this->form()->openTag($form); ?>
            <div class="row form-group">
                    <div class="col-xl-3"></div>
                    <div class="col-xl-2"><?= $this->formLabel($form->get('montant')); ?></div>
                    <div class="col-xl-4"><?= $this->formElement($form->get('montant')); ?></div>
                    <div class="col-xl-3">
                        <div class="invalid-feedback">
                            <?= $this->formElementErrors($form->get('montant')); ?>
                            Fcfa
                        </div>
                          
                    </div>
            </div>
        
            <div class="row form-group">
                <div class="col-xl-3"></div>
                <div class="col-xl-2"><?= $this->formLabel($form->get('remise')); ?></div>
                <div class="col-xl-4"><?= $this->formElement($form->get('remise')); ?></div>
                <div class="col-xl-3">
                    <div class="invalid-feedback">
                        <?= $this->formElementErrors($form->get('remise')); ?>
                    </div>
                </div>
            </div>
        
            <div class="row form-group">
                <div class="col-xl-3"></div>
                <div class="col-xl-2"><?= $this->formLabel($form->get('niveau')); ?></div>
                <div class="col-xl-4"><?= $this->formElement($form->get('niveau')); ?></div>
                <div class="col-xl-3">
                  
                    <!-- Modal -->
                    
                    <div class="invalid-feedback">
                        <?= $this->formElementErrors($form->get('niveau')); ?>
                    </div>
                </div>
            </div>
        
            <div class="row form-group">
                <div class="col-xl-3"></div>
                <div class="col-xl-2"><?= $this->formLabel($form->get('specialite')); ?></div>
                <div class="col-xl-4"><?= $this->formElement($form->get('specialite')); ?></div>
                <div class="col-xl-3">
                    
                    <!-- Modal -->
                    
                    <div class="invalid-feedback">
                        <?= $this->formElementErrors($form->get('specialite')); ?>
                    </div>
                </div>
            </div>
        
            <div class="row form-group">
                <div class="col-xl-3"></div>
                <div class="col-xl-2"><?= $this->formLabel($form->get('date')); ?></div>
                <div class="col-xl-4"><?= $this->formElement($form->get('date')); ?></div>
                <div class="col-xl-3">
                    
                    <!-- Modal -->
                    
                    <div class="invalid-feedback">
                        <?= $this->formElementErrors($form->get('date')); ?>
                    </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col-xl-3">
                    
                </div>
                <div class="col-xl-6 bg-light">
                    <?= $this->formElement($form->get('enregistrer')); ?>
                    <?= $this->formElement($form->get('annuler')); ?>                    
                </div>
                <div class="col-xl-3">
                    
                </div>
                
            </div> 
            <?= $this->form()->closeTag(); ?>
    </div>
    <!-- end card-body-->
</div>
