<?php $this->headTitle('prestations de service'); 

//var_dump($prestationsServices);
//die();
?>





<?php
$this->headTitle('Prestation de service');

$this->mainMenu()->setActiveItemId('prestations-service');
$this->mainMenu()->setDataTableAssets(true);
$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Users'=>$this->url('users'),
            ]);
?>
    
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h4 class="mb-0 font-size-18">Liste des prestations de service</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="<?= $this->url('admin'); ?>">Accueil</a></li>
                        <li class="breadcrumb-item active">Prestations de service</li>
                    </ol>
                </div>

            </div>
        </div>
    </div>   
    <div class="row">
        <div class="col-12">
                <?= $this->flashMessenger()->render('error', ['alert', 'alert-danger alert-dismissible fade show']); ?>
                <?= $this->flashMessenger()->render('success', ['alert', 'alert-success alert-dismissible fade show']); ?>
                <?= $this->flashMessenger()->render('info', ['alert', 'alert-info alert-dismissible fade show']); ?>
        </div>
        <div class="col-12">
            <div class="card">
                <div class="card-header"> 
                    <a class="btn btn-sm btn-primary float-right" href="<?= $this->url('admin', ['action'=>'ajouter-prestation']); ?>">
                      Ajouter une nouvelle prestation de service
                    </a> 
                </div>
                <div class="card-body">

                    <table id="formation-datatable" width='100%' class="table dt-responsive nowrap">
                        <thead>
                            <tr>
								<th> Libelle de la prestation </th>
								<th colspan="3"> Actions </th>
                            </tr>
                        </thead>
                        <tbody>

						<?php foreach($prestationsServices as $prestationsService){?>
								<tr> 
									<td><?=$prestationsService['libelle']?></td>
									<td colspan="1">
                                    <a class="btn btn-sm btn-warning" href="<?= $this->url('admin', ['action'=>'voir-prestation', 'id'=>$prestationsService['prestationServiceId']]); ?>">
                                        Détails
                                    </a>
                                </td>
                                <td colspan="1">
                                    <a class="btn btn-sm btn-success" href="<?= $this->url('admin', ['action'=>'editer-prestation', 'id'=>$prestationsService['prestationServiceId']]); ?>">
                                      Editer
                                    </a>
                                </td>
                                <td colspan="1">
                                    <a class="btn btn-sm btn-danger" href="<?= $this->url('admin', ['action'=>'supprimer-prestation', 'id'=>$prestationsService['prestationServiceId']]); ?>">
                                      Supprimer
                                    </a>
                                </td>
								</tr>
							<?php } ?>
                             
                        </tbody>
                    </table>

                </div> <!-- end card body-->
            </div> <!-- end card -->
        </div><!-- end col-->
    </div>
    <!-- end row-->
    
     
