<?php
$this->headTitle('Utilisateurs');

$this->mainMenu()->setActiveItemId('users');
$this->mainMenu()->setDataTableAssets(true);
$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Users'=>$this->url('users'),
            ]);
?>
    
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h4 class="mb-0 font-size-18">Détails de la formation</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Liste des formations</a></li>
                        <li class="breadcrumb-item active">Details</li>
                    </ol>
                </div>

            </div>
        </div>
    </div>   
    <div class="row">
        <div class="col-12">
                <?= $this->flashMessenger()->render('error', ['alert', 'alert-danger alert-dismissible fade show']); ?>
                <?= $this->flashMessenger()->render('success', ['alert', 'alert-success alert-dismissible fade show']); ?>
                <?= $this->flashMessenger()->render('info', ['alert', 'alert-info alert-dismissible fade show']); ?>
        </div>
        <div class="col-12">
            <div class="card">
                <!--div class="card-header"> 
                    <a class="btn btn-sm btn-primary float-right" href="< ?= $this->url('admin', ['action'=>'ajouter-formation']); ?>">
                      Ajouter une nouvelle formation
                    </a> 
                </div-->
                <div class="card-body">

                    <table id="formation-datatable" width='100%' class="table dt-responsive nowrap">
                        <thead class="bg-secondary text-white">
                            <tr>
                                <th>Intitulé de la formation</th>
                                <th>Date de début</th>
                                <th>Date de fin</th>
                                <th>Lieu</th>
                                <th>Date de création</th>
                                <th>Type de formation</th>
                            </tr>
                        </thead>
                        <tbody class="bg-light">
                            
                            <tr>
                                <td>
                                    <?= $formation['formation']->getLibelle();?>
                                </td>
                                <td>
                                    <?= $formation['formation']->getDateDebut();?>
                                </td>
                                <td>
                                    <?= $formation['formation']->getDateFin();?>
                                </td>
                                <td>
                                    <?= $formation['formation']->getLieu();?>
                                </td>
                                <td>
                                    <nobr><?= $formation['formation']->getDateCreation();?></nobr>
                                </td>
                                <td>
                                    <?= $formation['type']->getLibelle();?>
                                </td>
                            </tr>
                        </tbody>
                    </table>

                </div> <!-- end card body-->
            </div> <!-- end card -->
        </div><!-- end col-->
    </div>
    <!-- end row-->


    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header"> 
                    <a class="btn btn-sm btn-success float-right" href="<?= $this->url('admin', ['action'=>'ajouter-condition','id'=>($formation['formation'])->getFormationId()]); ?>">
                        Ajouter une nouvelle condition
                    </a> 
                    
                </div>
                <div class="card-body">
                    <p> liste des conditions </p> 
                    <table id="formation-datatable" width='100%' class="table dt-responsive nowrap">
                        <thead>
                            <tr>
                                <th>Montant total de la formation</th>
                                <th>Remise</th>
                                <th>Niveau Minimum requis</th>
                                <th>Spécialités</th>
                                <th>Date d'échéance d'inscription</th>
                                <th colspan="2">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            <?php 
                            $conditions = $formation['conditions'];
                            //var_dump($conditions);die();
                            if($conditions){
                            foreach($conditions as $condition){
                            ?>
                            <tr>
                                <td>
                                    <?= $condition['montant'];?>
                                </td>
                                <td>
                                    <?= $condition['remise'];?>
                                </td>
                                <td>
                                    <?= ($condition['niveau'])->getLibelle();?>
                                </td>
                                <td>
                                    <?= ($condition['profession'])->getLibelle();?>
                                </td>
                                <td>
                                    <?= $condition['date'] ;?>
                                    <!--?= $this->dateFormat($condition['date'],IntlDateFormatter::LONG) ;?-->
                                </td>
                                <td colspan="1">
                                    <a class="btn btn-sm btn-success" href="<?= $this->url('admin', ['action'=>'editer-condition', 'id'=>$condition['cndParticipationId']]); ?>">
                                      Editer
                                    </a>
                                </td>
                                <td colspan="1">
                                    <a class="btn btn-sm btn-danger" href="<?= $this->url('admin', ['action'=>'supprimer-condition', 'id'=>$condition['cndParticipationId']]); ?>">
                                      Supprimer
                                    </a>
                                </td>
                            </tr>
                            <?php
                                }
                            }
                            else{
                                echo '<td class="text-danger h4"> Vous n\'avez enregistré aucune conditions de participation </td>';
                            }
                            ?>
                        </tbody>
                    </table>

                </div> <!-- end card body-->
            </div> <!-- end card -->
        </div><!-- end col-->
    </div>
    <!-- end row-->


    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header"> 
                    <a class="btn btn-sm btn-warning float-right" href="<?= $this->url('admin', ['action'=>'ajouter-module','id'=>($formation['formation'])->getFormationId()]); ?>">
                      Ajouter un nouveau module
                    </a> 
                </div>
                <div class="card-body">
                    <p> liste des modules </p> 
                    <table id="formation-datatable" width='100%' class="table dt-responsive nowrap">
                        <thead>
                            <tr>
                                <th>Libelle</th>
                                <th>Contenu</th>
                                <th>Coût du module</th>
                                <th colspan="2">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php 
                                $modules = $formation['modules'];
                                if($modules){
                                foreach($modules as $module){
                            ?>
                            <tr>
                                <td>
                                    <?= $module->getLibelle();?>
                                </td>
                                <td>
                                    <?= $module->getContenu();?>
                                </td>
                                <td>
                                    <?= $module->getCout();?>
                                </td>
                                <td colspan="1">
                                    <a class="btn btn-sm btn-success" href="<?= $this->url('admin', ['action'=>'editer-module', 'id'=>$module->getModuleId()]); ?>">
                                      Editer
                                    </a>
                                </td>
                                <td colspan="1">
                                    <a class="btn btn-sm btn-danger" href="<?= $this->url('admin', ['action'=>'supprimer-module', 'id'=>$module->getModuleId()]); ?>">
                                      Supprimer
                                    </a>
                                </td>
                            </tr>
                            <?php
                                }
                            }
                            else{
                                echo '<td class="text-danger h4"> Vous n\'avez enregistré aucun module </td>';
                            }
                            ?>  
                        </tbody>
                    </table>

                </div> <!-- end card body-->
            </div> <!-- end card -->
        </div><!-- end col-->
    </div>
    <!-- end row-->