<?php
$this->headTitle('Détails');

$this->mainMenu()->setActiveItemId('users');
$this->mainMenu()->setDataTableAssets(true);
$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Users'=>$this->url('users'),
            ]);
?>
    
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h4 class="mb-0 font-size-18">Détails de la prestation de service</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="<?= $this->url('admin', ['action'=>'prestations-service']); ?>">Liste des prestations de service</a></li>
                        <li class="breadcrumb-item active">Détails</li>
                    </ol>
                </div>

            </div>
        </div>
    </div>   
    <div class="row">
        <div class="col-12">
                <?= $this->flashMessenger()->render('error', ['alert', 'alert-danger alert-dismissible fade show']); ?>
                <?= $this->flashMessenger()->render('success', ['alert', 'alert-success alert-dismissible fade show']); ?>
                <?= $this->flashMessenger()->render('info', ['alert', 'alert-info alert-dismissible fade show']); ?>
        </div>
        <div class="col-12">
            <div class="card">
                <!--div class="card-header"> 
                    <a class="btn btn-sm btn-primary float-right" href="< ?= $this->url('admin', ['action'=>'ajouter-prestation']); ?>">
                      Ajouter une nouvelle prestation
                    </a> 
                </div-->
                <div class="card-body">

                    <table id="prestation-datatable" width='100%' class="table dt-responsive nowrap">
                        <thead class="bg-secondary text-white">
                            <?php 
                                $laPrestation = $prestation['prestation'];
                            ?>
                            <tr>
                                <th>Libellé de la prestation de service</th>
                            </tr>
                        </thead>
                        <tbody class="bg-light">
                            
                            <tr>
                                <td>
                                    <?= $laPrestation->getLibelle();?>
                                </td>
                               
                            </tr>
                        </tbody>
                    </table>

                </div> <!-- end card body-->
            </div> <!-- end card -->
        </div><!-- end col-->
    </div>
    <!-- end row-->


    <div class="row">
        <div class="col-12">
            <div class="card">

                <div class="card-header"> 
                    <a class="btn btn-sm btn-success float-right" href="<?= $this->url('admin', ['action'=>'ajouter-section','id'=>$laPrestation->getServiceId()]); ?>">
                        Ajouter une nouvelle section
                    </a> 
                    
                </div>
                <div class="card-body">
                    <p> liste des sections </p> 
                    <table id="prestation-datatable" width='100%' class="table dt-responsive nowrap">
                        <thead>
                            <tr>
                                <th>Libelle</th>
                                <th>Text du contenu</th>
                                <th colspan="2">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            <?php 
                            $sections = $prestation['sections'];
                            //var_dump($prestations);die();
                            if($sections){
                            foreach($sections as $section){
                            ?>
                            <tr>
                                <td>
                                    <?= $section->getLibelle();?>
                                </td>
                                <td>
                                    <?= $section->getText();?>
                                </td>
                                <td colspan="1">
                                    <a class="btn btn-sm btn-success" href="<?= $this->url('admin', ['action'=>'editer-section', 'id'=>$section->getSectionId()]); ?>">
                                      Editer
                                    </a>
                                </td>
                                <td colspan="1">
                                    <a class="btn btn-sm btn-danger" href="<?= $this->url('admin', ['action'=>'supprimer-section', 'id'=>$section->getSectionId()]); ?>">
                                      Supprimer
                                    </a>
                                </td>
                            </tr>
                            <?php
                                }
                            }
                            else{
                                echo '<td class="text-danger h4"> Vous n\'avez enregistré aucune section pour cette prestation de service </td>';
                            }
                            ?>
                        </tbody>
                    </table>

                </div> <!-- end card body-->
            </div> <!-- end card -->
        </div><!-- end col-->
    </div>
    <!-- end row-->