<?php
$this->headTitle('Ajouter une formation');

$this->mainMenu()->setActiveItemId('formation');

$this->pageBreadcrumbs()->setItems([
            'Accueil'=>$this->url('admin')
            ]);
////var_dump($form);die();
 $form->get('image')->setAttributes([
    'class'=>'form-control', 
    
    ]);
 
 $form->get('titre')->setAttributes([
    'class'=>'form-control',
    
    ]);
 
 $form->get('libelle')->setAttributes([
    'class'=>'form-control', 
    
    ]);
 
 $form->get('libelleBtn')->setAttributes([
    'class'=>'form-control',
    ]);
 
 $form->get('routeBtn')->setAttributes([
    'class'=>'form-control',
    'data-toggle'=>'select2', 
    ]);
 
 $form->get('enregistrer')->setAttributes([
    'class'=>'btn btn-sm btn-success waves-effect waves-light float-right',
    ]);
 $form->get('annuler')->setAttributes([
    'class'=>'btn btn-sm btn-danger waves-effect waves-light float-left',
    ]);
 
 
//$form->prepare();

?>
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0 font-size-18">Ajout d'un slide </h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Slide</a></li>
                    <li class="breadcrumb-item active">Slide</li>
                </ol>
            </div>

        </div>
    </div>
    <div class="col-12">
            <?= $this->flashMessenger()->render('error', ['alert', 'alert-danger alert-dismissible fade show']); ?>
            <?= $this->flashMessenger()->render('success', ['alert', 'alert-success alert-dismissible fade show']); ?>
            <?= $this->flashMessenger()->render('info', ['alert', 'alert-info alert-dismissible fade show']); ?>
    </div>
</div>  
<div class="card">
    <div class="card-body" style="padding-top: 50px; padding-bottom: 50px;">
       
        <!--?= $this->form()->openTag($form); ?-->
        <form method="post" enctype="multipart/form-data">
            
            <div class="row form-group">

                <div class="col-xl-3"></div>
                    <div class="col-xl-2"><?= $this->formLabel($form->get('image')); ?></div>
                    <div class="col-xl-4"><?= $this->formElement($form->get('image')); ?></div>
                    <div class="col-xl-3"><div class="hint">(Format autorisés : PNG, JPG et JPEG )</div>
                        <div class="invalid-feedback">
                            <?= $this->formElementErrors($form->get('image')); ?>
                        </div>
                </div>
            </div>
        
            <div class="row form-group">
                <div class="col-xl-3"></div>
                <div class="col-xl-2"><?= $this->formLabel($form->get('titre')); ?></div>
                <div class="col-xl-4"><?= $this->formElement($form->get('titre')); ?></div>
                <div class="col-xl-3">
                    <div class="invalid-feedback">
                        <?= $this->formElementErrors($form->get('titre')); ?>
                    </div>
                </div>
            </div>

            <div class="row form-group">
                <div class="col-xl-3"></div>
                <div class="col-xl-2"><?= $this->formLabel($form->get('libelle')); ?></div>
                <div class="col-xl-4"><?= $this->formElement($form->get('libelle')); ?></div>
                <div class="col-xl-3">
                    <div class="invalid-feedback">
                        <?= $this->formElementErrors($form->get('libelle')); ?>
                    </div>
                </div>
            </div>
        
            <div class="row form-group">
                <div class="col-xl-3"></div>
                <div class="col-xl-2"><?= $this->formLabel($form->get('libelleBtn')); ?></div>
                <div class="col-xl-4"><?= $this->formElement($form->get('libelleBtn')); ?></div>
                <div class="col-xl-3">
                    
                    <div class="invalid-feedback">
                        <?= $this->formElementErrors($form->get('libelleBtn')); ?>
                    </div>
                </div>
            </div>
        
            <div class="row form-group">
                <div class="col-xl-3"></div>
                <div class="col-xl-2"><?= $this->formLabel($form->get('routeBtn')); ?></div>
                <div class="col-xl-4"><?= $this->formElement($form->get('routeBtn')); ?></div>
                <div class="col-xl-3">
                    
                    <div class="invalid-feedback">
                        <?= $this->formElementErrors($form->get('routeBtn')); ?>
                    </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col-xl-3">
                    
                </div>
                <div class="col-xl-6 bg-light">
                    <?= $this->formElement($form->get('enregistrer')); ?>
                    <?= $this->formElement($form->get('annuler')); ?>                    
                </div>
                <div class="col-xl-3">
                    
                </div>
                
            </div> 
            <!--?= $this->form()->closeTag(); ?-->
        </form>
    </div>
    <!-- end card-body-->
</div>
