<?php $this->HeadTitle('formations');?> 
<div class="row">
   
                <div class="col-lg-3 bg-transparent">
                    <h2></h2>
                </div>
                <div class="col-lg-6 bg-danger text-justify">
                       <h2 class="text-justify">Programme de formation</h2>
                </div>
                <div class="col-lg-3 bg-transparent">
                       <h2></h2>
                </div>
</div>