<?php $this->headTitle('services'); ?>
    <!----section services---->	
    <section class="ftco-section">
			<div class="container">
				<div class="row justify-content-center mb-5 pb-2">
          <div class="col-md-8 text-center heading-section ftco-animate">
            <h2 class="mb-4 text-danger">Meilleurs Services</h2>
            <p>NOS PRESTATIONS</p>
          </div>
        </div>
				<div class="row no-gutters">
					<div class="col-lg-4 d-flex">
						<div class="services-2 noborder-left text-center ftco-animate">
							<div class="icon mt-2 d-flex justify-content-center align-items-center"><span class="flaticon-collaboration "></span></div>
							<div class="text media-body">
								<h3>MUTUALITE/VIE ASSOCIATIVE</h3>
                                                                <ul>
                                                                    <li class="text-left"><p><span class="font-weight-bold text-uppercase">Constitution</span>: Etude de faisabilité, sensibilisations, mise en place des organes dirigeants, rédaction des textes statutaires,organisation d'assemblée générale, établissement du dossier pour obtention de l'agrément aupès des organes habilités</p></li>
                                                                    <li class="text-left"><p><span class="font-weight-bold text-uppercase" >Assistance en Gestion</span>: Mise en place de la gestion du système de santé(mutuelles sociales); Suivi administratif juridique et financier (rédation d'actes juridiques, suivi comptable et fiscal);Evaluation et suivi du système interne de gestion</p></li>
                                                                    <li class="text-left"><p><span class="font-weight-bold text-uppercase">Coaching en développement</span>(stratégies de développemnt, de négociation et marketing, développement du capital humain)</p></li>
                                                                 </ul>
								
							</div>
						</div>
					</div>
					<div class="col-lg-4 d-flex">
						<div class="services-2 text-center ftco-animate">
							<div class="icon mt-2 d-flex justify-content-center align-items-center"><span class="flaticon-handshake"></span></div>
							<div class="text media-body">
								<h3>ACCOMPAGNEMENT JURIDIQUE</h3>
								<ul> 
                                                                    <li class="text-">Conseils et consultations juridiques</li> <br><br><br>
                                                                    <li class="text-left">Analyse et rédaction d’actes juridiques et veille juridique</li> <br><br><br>
                                                                    <li class="text-left">Création de société(établissement du dossier pour la création, suivi des démarches auprès du cepici</li><br><br><br> 
                                                                    <li class="text-left">Recouvrement amiable et judiciaire</li>
                                                                </ul>
							</div>
						</div>
					</div>
					<div class="col-lg-4 d-flex">
						<div class="services-2 text-center ftco-animate">
							<div class="icon mt-2 d-flex justify-content-center align-items-center"><span class="flaticon-money"></span></div>
							<div class="text media-body">
								<h3>COMPTABILITE ET FISCALILITE</h3>
								<ul> 
                                                                    <li class="text-left">Etats financiers</li> <br><br><br>
                                                                    <li class="text-left">Suivi comptable et fiscal</li> <br><br><br><br>
                                                                     <li class="text-left">Déclarations comptables, fiscales et sociales</li>
                                                                </ul>
							</div>
						</div>
					</div>
					<div class="col-lg-4 d-flex">
						<div class="services-2 noborder-left noborder-bottom text-center ftco-animate">
							<div class="icon mt-2 d-flex justify-content-center align-items-center"><span class="flaticon-search-engine"></span></div>
							<div class="text media-body">
								<h3>COACHING/ENTREPRENARIAT</h3>
								<ul> 
                                                                    <li class="text-left">Coaching individuel</li><br><br><br> 
                                                                    <li class="text-left">Coaching d’équipe</li> <br><br><br>                                                                 
                                                                    <li class="text-left">Initiation à l’entreprenariat et stratégies de développement</li>
                                                                </ul>
							</div>
						</div>
					</div>
					<div class="col-lg-4 d-flex">
						<div class="services-2 text-center noborder-bottom ftco-animate">
							<div class="icon mt-2 d-flex justify-content-center align-items-center"><span class="flaticon-insurance"></span></div>
							<div class="text media-body">
								<h3>FORMATIONS</h3>
								<ul> 
                                                                    <li class="text-left">Mutualité, protection et sécurité sociale, ressources  humaines,développemnt personnel </li><br>
                                                                    <li class="text-left">Marketing, management, communication, gestion, finance, informatique et TIC</li> <br>
                                                                    <li class="text-left">Droit, comptabilité, fiscalité, audit, entreprenariat, assistanat de direction,secrétariat, informatique et digital etc.</li> <br>
                                                                    <li class="text-left">Team bulding, séminaires, conférences, ateliers etc.</li>
                                                                </ul>
							</div>
						</div>
					</div>
					<div class="col-lg-4 d-flex">
						<div class="services-2 text-center noborder-bottom ftco-animate">
							<div class="icon mt-2 d-flex justify-content-center align-items-center"><span class="flaticon-rating"></span></div>
							<div class="text media-body">
								<h3>Marketing Strategy</h3>
								<ul> 
                                                                    <li class="text-leftt"></li> 
                                                                    <li class="text-leftt"></li> 
                                                                    <li class="text-leftt"></li> 
                                                                    <li class="text-leftt"></li>
                                                                </ul>
							</div>
						</div>
					</div>
			</div>
		</section><!----end section service---->
    
   <section class="ftco-intro ftco-no-pb img" style="background-image: url(img/bg_1.jpg);">
        <div class="container">
            <div class="row justify-content-center">
               <div class="col-lg-9 col-md-8 d-flex align-items-center heading-section heading-section-white ftco-animate">
                  <marquee behavior="scroll"><h2 class="mb-3 mb-md-0 text-white">Vous obtenez toujours les meilleurs conseils!</h2></marquee>
                  </div>
              <!--<div class="col-lg-3 col-md-4 ftco-animate">
                    <p class="mb-0"><a href="#" class="btn btn-white py-3 px-4">Request Quote</a></p>
                </div>-->
             </div>	
        </div>
    </section><!----end section banière---->                                                                   
   
