<?php

$form->get('email')->setAttributes([
    'class'=>'form-control form-control-user', 
    'id' => 'exampleInputEmail',
    'placeholder'=>'Adresse email',
    'required' => true,
    'autofocus' => true
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('password')->setAttributes([
    'class'=>'form-control form-control-user', 
    'id' => 'exampleInputPassword', 
    'placeholder'=>'Mot de passe',
    'required' => true,
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);
?>

<!doctype html>
<html lang="">

<head>
    <meta charset="utf-8" />
    <title>Connexion - GestParc</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="MyraStudio" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- favicon
		============================================ -->
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->basePath().'img/logogr/logogr1.jpg';?>">
    <link href="<?php echo $this->basePath().'/assets/css/bootstrap.min.css';?>" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->basePath().'/assets/css/icons.min.css';?>" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->basePath().'/assets/css/theme.min.css';?>" rel="stylesheet" type="text/css" />
        
    <script src="<?php echo $this->basePath().'/assets/js/vendor/modernizr-2.8.3.min.js';?>"></script>
</head>
<body>
    
    <div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="d-flex align-items-center min-vh-100">
                        <div class="w-100 d-block bg-white shadow-lg rounded my-5">
                            <div class="row">
                                <div class="col-lg-5 d-none d-lg-block bg-login rounded-left"></div>
                                <div class="col-lg-7">
                                    <div class="p-5">
                                        <div class="text-center mb-5" >
                                            <a href="<?= $this->url('home'); ?>" class="logo" >
                                                <img style="background-color: #3cb371;border-radius: 50px 20px;" height="70px" src="<?php echo $this->basePath().'img/logogr/logogr2.jpg';?>">
                                            </a>
                                        </div>
                                        <?php if ($isLoginError): ?>
                                        <div class="alert alert-warning" role="alert">
                                            Login et/ou mot de passe incorrecte. 
                                            <a href="<?= $this->url('reset-password') ?>">Mot de passe oublié?</a>
                                        </div>
                                        <?php endif; ?>
                                        <h1 class="h5 mb-1">Bienvenue!</h1>
                                        <p class="text-muted mb-4">Entrez votre email et votre mot de passe pour accéder à l'application.</p>
                                        <form class="user" method="post">
                                            <div class="form-group">
                                                <?= $this->formElement($form->get('email')); ?>
                                            </div>
                                            <div class="form-group">
                                                <?= $this->formElement($form->get('password')); ?>
                                            </div>
                                            <button type="submit" style="background-color: #bd1522;" class="btn btn-block waves-effect waves-light text-white"> Se connecter </button>
                                            <?= $this->formElement($form->get('redirect_url')); ?>
                                            <?= $this->formElement($form->get('csrf')) ?>
                                        </form>

                                        <div class="row mt-4">
                                            <div class="col-12 text-center">
                                                <p class="text-muted mb-2"><a href="<?= $this->url('reset-password') ?>" class="text-muted font-weight-medium ml-1">Mot de passe oublié?</a></p>
                                                <p class="text-muted mb-0">Vous n'avez pas de compte ? <a href="<?= $this->url('reset-password') ?>" class="text-muted font-weight-medium ml-1"><b>Créez en</b></a></p>
                                            </div> <!-- end col -->
                                        </div>
                                        <!-- end row -->
                                    </div> <!-- end .padding-5 -->
                                </div> <!-- end col -->
                            </div> <!-- end row -->
                        </div> <!-- end .w-100 -->
                    </div> <!-- end .d-flex -->
                </div> <!-- end col-->
            </div> <!-- end row -->
        </div>
        <!-- end container -->
    </div>
    <!-- end page -->
    <script src="<?php echo $this->basePath().'/assets/js/jquery.min.js';?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath().'/assets/js/bootstrap.bundle.min.js';?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath().'/assets/js/metismenu.min.js';?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath().'/assets/js/waves.js';?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath().'/assets/js/simplebar.min.js';?>"></script>
    <script src="<?php echo $this->basePath().'/assets/js/theme.js';?>" type="text/javascript"></script>
</body>

</html>