<?= $this->doctype() ?>

<html lang="fr">
    <head>
          <meta charset="utf-8">
          
         <?= $this->headTitle('G&Rconsult')->setSeparator(' - ')->setAutoEscape(false) ?>
         <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
 
            <meta content="" name="descriptison">
            <meta content="" name="keywords">
        
         <!-- Favicons -->
    <link href="<?=$this->basePath('img/logogr/logogr1.jpg')?>" rel="icon">
    <link href="<?=$this->basePath('img/logogr/logogr1.jpg')?>" rel="apple-touch-icon">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,600,700,800,900&display=swap" rel="stylesheet">
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">-->
    <link rel="stylesheet" href="<?=$this->basePath('css/open-iconic-bootstrap.min.css')?>">
    <link rel="stylesheet" href="<?=$this->basePath('css/animate.css')?>">
    <link rel="stylesheet" href="<?=$this->basePath('css/owl.carousel.min.css')?>">
    <link rel="stylesheet" href="<?=$this->basePath('css/owl.theme.default.min.css')?>">
    <link rel="stylesheet" href="<?=$this->basePath('css/magnific-popup.css')?>">
    <link rel="stylesheet" href="<?=$this->basePath('css/aos.css')?>">
    <link rel="stylesheet" href="<?=$this->basePath('css/ionicons.min.css')?>">
    <link rel="stylesheet" href="<?=$this->basePath('css/flaticon.css')?>">
    <link rel="stylesheet" href="<?=$this->basePath('css/icomoon.css')?>">
    
    
    <!-- Template Main CSS File -->
    <link rel="stylesheet" href="<?=$this->basePath('css/style.css')?>">
    </head>
    <body>
                <!-- ======= Header ======= -->
        <div class="bg-top navbar-light">
    	<div class="container">
    		<div class="row no-gutters d-flex align-items-center align-items-stretch">
                    <div class="col-md-4 d-flex align-items-center py-4"><br>
                            <a class="navbar-brand text-danger rounded float-left"><img src="img/logogr/logogr3.jpg"</img><br>Gabriel & Raphële Consulting</a>
    			</div>
	    		<div class="col-lg-8 d-block">
		    		<div class="row d-flex">
					    <div class="col-md d-flex topper align-items-center align-items-stretch py-md-4">
					    	<div class="icon d-flex justify-content-center align-items-center"></div>
					    	<div class="text">
                                                    <span class="text-danger icon-paper-plane">  infos@grconsult.ci</span>                                          
						    </div>
					    </div>
					    <div class="col-md d-flex topper align-items-center align-items-stretch py-md-4">
					    	<div class="icon d-flex justify-content-center align-items-center"></div>
						    <div class="text">
                                                        <span class="text-danger icon-phone">  (+225) 22015889 / 0595407894</span><br>                                     
                                                           <span class="text-danger icon-calendar font-weight-bold"> Ouvert Du Lundi au vendredi: 8h-18h</span>       
                                                  </div>
					    </div>
					 
				    </div>
			    </div>
		    </div>
		  </div>
    </div>
	  <nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light" id="ftco-navbar">
                <div class="container d-flex align-items-center">
                      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="oi oi-menu"></span> Menu
                      </button>
                    <div class="collapse navbar-collapse" id="ftco-nav">
                            <ul class="navbar-nav mr-auto">
                                    <li class="nav-item"><a href="<?=$this->basePath('')?>" class="nav-link pl-0 text fw-bold">Accueil</a></li>
                                    <li class="nav-item"><a href="<?=$this->basePath('nous-connaitre')?>" class="nav-link">Nous connaître</a></li>
                                    <li class="nav-item"><a href="<?=$this->basePath('prestations-service')?>" class="nav-link">Prestations</a></li>
                                     <li class="nav-item"><a href="#" class="nav-link">Formations</a></li>  <!-- ?=$this->basePath('formations')? -->
                                     <li class="nav-item"><a href="#" class="nav-link">Galerie</a></li> <!--?=$this->basePath('galerie')? -->
                                     <li class="nav-item"><a href="<?=$this->basePath('contact')?>" class="nav-link">Contact</a></li> 
                            </ul>
                    </div>    
                       
                </div>
                
	  </nav>
        <!-- End Header--->
        
           <?= $this->content ?> 
        	
    <!--<section class="ftco-intro ftco-no-pb img" style="background-image: url(img/bg_1.jpg);">
    	<div class="container">
    		<div class="row justify-content-center">
            <div class="col-lg-9 col-md-8 d-flex align-items-center heading-section heading-section-white ftco-animate">
              <marquee behavior="scroll"><h2 class="mb-3 mb-md-0 text-white">Vous obtenez toujours les meilleurs conseils!</h2></marquee>
              </div>
           </div>	
    	</div>
    </section><!----end section banière---->
    
    <!--<section class="ftco-section testimony-section">
                <div class="container">
                  <div class="row justify-content-center mb-5">
                    <div class="col-md-8 text-center heading-section ftco-animate">
                      <h2 class="mb-4 text-danger">Clients & Partenaires</h2>
                      <p>Ils nous ont fait confiance!</p>
                    </div>
                  </div>
                    <div class="row ftco-animate justify-content-center">
                      <div class="col-md-12">
                        <div class="carousel-testimony owl-carousel">
                          <div class="item">
                            <div class="testimony-wrap d-flex">
                              <div class="user-img" style="background-image: url(img/testyimg/dgemci.png)">
                              </div>
                              <div class="text pl-4">
                                    <span class="quote d-flex align-items-center justify-content-center">
                                  <i class="icon-quote-left"></i>
                                </span>
                                <p>Direction Générale des Ecoles Méthodistes.</p>
                                <p class="name font-weight-bold">DGEMCI</p>
                                <span class="position text-danger font-italic">Ils nous ont fait confiance!</span>
                              </div>
                            </div>
                          </div>
                          <div class="item">
                            <div class="testimony-wrap d-flex">
                              <div class="user-img" style="background-image: url(img/testyimg/meemci.png)">
                              </div>
                              <div class="text pl-4">
                                    <span class="quote d-flex align-items-center justify-content-center">
                                  <i class="icon-quote-left"></i>
                                </span>
                                <p>Mutuelle des Employes des Ecoles Méthodistes.</p>
                                <p class="name font-weight-bold">MEEM-CI</p>
                                <span class="position text-danger font-italic">Ils nous ont fait confiance!</span>
                              </div>
                            </div>
                          </div>
                          <div class="item">
                            <div class="testimony-wrap d-flex">
                              <div class="user-img" style="background-image: url(img/testyimg/maabs.png)">
                              </div>
                              <div class="text pl-4">
                                    <span class="quote d-flex align-items-center justify-content-center">
                                  <i class="icon-quote-left"></i>
                                </span>
                                <p>Mutuelle des agents maab santé</p>
                                <p class="name text font-weight-bold">MAABSanté</p>
                                <span class="position text-danger font-italic">Ils nous ont fait confiance!</span>
                              </div>
                            </div>
                          </div>
                          <div class="item">
                            <div class="testimony-wrap d-flex">
                              <div class="user-img" style="background-image: url(img/testyimg/musarti.png)">
                              </div>
                              <div class="text pl-4">
                                    <span class="quote d-flex align-items-center justify-content-center">
                                  <i class="icon-quote-left"></i>
                                </span>
                                <p>Mutuelle Sociale des Agents de la RTI.</p>
                                <p class="name font-weight-bold">MUSARTI</p>
                                <span class="position text-danger font-italic">Ils nous ont fait confiance!</span>
                              </div>
                            </div>
                          </div>
                          <div class="item">
                            <div class="testimony-wrap d-flex">
                              <div class="user-img" style="background-image: url(img/testyimg/mupartci.png)">
                              </div>
                              <div class="text pl-4">
                                    <span class="quote d-flex align-items-center justify-content-center">
                                  <i class="icon-quote-left"></i>
                                </span>
                                <p>Mutuelle du Personnel de l'ARTCI.</p>
                                <p class="name font-weight-bold">MUPARTCI</p>
                                <span class="position text-danger font-italic">Ils nous ont fait confiance!</span>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
    </section>  <!----section clients et partenaires---->

        
        <!--Footer section--->
     <footer class="ftco-footer ftco-bg-dark  ftco-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-6 col-lg-4">
            <div class="ftco-footer-widget mb-5">
            	<h2 class="ftco-heading-2 text-danger">ADRESSE</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">Akouedo Est, route de Bingerville (non loin de la pharmacie Jules Verne) immeuble ONEP BS, 3ème étage, porte n°2 à gauche</span></li>
	                <li><a><span class="icon icon-phone"></span><span class="text">+225 22 01 85 93 / 0555997359 / 0544879113</span></a></li>
	                <li><a><span class="icon icon-envelope"></span><span class="text">info@grconsult.ci</span></a></li>
                        <li><a><span class="icon icon-map-marker"></span><span class="text">01 BP 6687 Abidjan 01</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>        
          <div class="col-md-6 col-lg-4">
            <div class="ftco-footer-widget mb-5 ml-md-4">
              <h2 class="ftco-heading-2 text-danger ">LIENS UTILS</h2>
              <ul class="list-unstyled">
                <li><a href="<?=$this->basePath('')?>"><span class="ion-ios-arrow-round-forward mr-2"></span>Acceuil</a></li>
                <li><a href="<?=$this->basePath('nous-connaitre')?>"><span class="ion-ios-arrow-round-forward mr-2"></span>Nous connaître</a></li>
                <li><a href="<?=$this->basePath('prestations-service')?>"><span class="ion-ios-arrow-round-forward mr-2"></span>Prestations</a></li>
                <li><a href="<?=$this->basePath('formations')?>"><span class="ion-ios-arrow-round-forward mr-2"></span>Formations</a></li>
                <li><a href="<?=$this->basePath('galerie')?>"><span class="ion-ios-arrow-round-forward mr-2"></span>Galerie</a></li>
                <li><a href="<?=$this->basePath('contact')?>"><span class="ion-ios-arrow-round-forward mr-2"></span>Contact</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-6 col-lg-4">
            <div class="ftco-footer-widget mb-5">
            	<h2 class="ftco-heading-2 text-danger">RESEAUX SOCIAUX </h2>
             <!-- <form action="#" class="subscribe-form">
                <div class="form-group">
                  <input type="text" class="form-control mb-2 text-center" placeholder="Enter email address">
                  <input type="submit" value="Subscribe" class="form-control submit px-3">
                </div>
              </form>-->
            </div>
            <div class="ftco-footer-widget mb-5">
            	<h2 class="ftco-heading-2 mb-0">Suivez-nous avec</h2>
            	<ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-3">
                <li class="ftco-animate"><a href="#"><span class="icon-linkedin"></span></a></li>
                <li class="ftco-animate"><a href=""><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> Tout Droit Réservé| Gabriel & Rachèle Consulting <i class="icon-calendar" aria-hidden="true"></i> by <a href="https://www.grconsult.ci" target="_blank">G&R Consult</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </footer>
        <!--End Footer--->
        <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>
         
         <!-- JS Files -->
  <script src="<?=$this->basePath('js/jquery.min.js')?>"></script>
  <script src="<?=$this->basePath('js/jquery-migrate-3.0.1.min.js')?>"></script>
  <script src="<?=$this->basePath('js/popper.min.js')?>"></script>
  <script src="<?=$this->basePath('js/bootstrap.min.js')?>"></script>
  <script src="<?=$this->basePath('js/jquery.easing.1.3.js')?>"></script>
  <script src="<?=$this->basePath('js/jquery.waypoints.min.js')?>"></script>
  <script src="<?=$this->basePath('js/jquery.stellar.min.js')?>"></script>
  <script src="<?=$this->basePath('js/owl.carousel.min.js')?>"></script>
  <script src="<?=$this->basePath('js/jquery.magnific-popup.min.js')?>"></script>
  <script src="<?=$this->basePath('js/aos.js')?>"></script>
  <script src="<?=$this->basePath('js/jquery.animateNumber.min.js')?>"></script>
  <script src="<?=$this->basePath('js/scrollax.min.js')?>"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="js/google-map.js"></script>
 <!--glyfon icon-->
 <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>-->
  <!-- Template Main JS File -->
  <script src="<?=$this->basePath('js/main.js')?>"></script>   
    </body>
</html>
