<?php
$this->headTitle('Ajouter Permission');

$this->mainMenu()->setActiveItemId('admin');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Permissions'=>$this->url('permissions'),
            'Add Permission'=>$this->url('permissions', ['action'=>'add'])
            ]);

$form->get('name')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('description')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary',
    'style'=>'background-color: #1bbc9b;color:white;']);

$form->prepare();
?>
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0 font-size-18">Ajout de permission</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Pages</a></li>
                    <li class="breadcrumb-item active">Elements</li>
                </ol>
            </div>

        </div>
    </div>
</div><div class="card">
    <div class="card-body">
       
        <?= $this->form()->openTag($form); ?>
            <div class="row form-group">
                <div class="col-xl-2"></div>
                <div class="col-xl-2"><?= $this->formLabel($form->get('name')); ?></div>
                <div class="col-xl-5"><?= $this->formElement($form->get('name')); ?></div>
                <div class="col-xl-3">
                    <div class="invalid-feedback">
                        <?= $this->formElementErrors($form->get('name')); ?>
                    </div>
                </div>
            </div>
        
            <div class="row form-group">
                <div class="col-xl-2"></div>
                <div class="col-xl-2"><?= $this->formLabel($form->get('description')); ?></div>
                <div class="col-xl-5"><?= $this->formElement($form->get('description')); ?></div>
                <div class="col-xl-3">
                    <div class="invalid-feedback">
                        <?= $this->formElementErrors($form->get('description')); ?>
                    </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col-xl-5">
                    
                </div>
                <div class="col-xl-6">
                    <?= $this->formElement($form->get('csrf')); ?>
                        <?= $this->formElementErrors($form->get('csrf')); ?>
                        <?= $this->formElement($form->get('submit')); ?>
                        <input type="reset" class="btn btn-danger" name="" value="Annuler">
                </div>
                
            </div> 
            <?= $this->form()->closeTag(); ?>
    </div>
    <!-- end card-body-->
</div>