<?php
$this->headTitle('Détails');

$this->mainMenu()->setActiveItemId('users');
$this->mainMenu()->setDataTableAssets(true);
$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Users'=>$this->url('users'),
            ]);
?>
    
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h4 class="mb-0 font-size-18">Détails du message</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="<?= $this->url('messages'); ?>">Liste des messages</a></li>
                        <li class="breadcrumb-item active">Détails</li>
                    </ol>
                </div>

            </div>
        </div>
    </div>   
    <div class="row">
        <div class="col-12">
                <?= $this->flashMessenger()->render('error', ['alert', 'alert-danger alert-dismissible fade show']); ?>
                <?= $this->flashMessenger()->render('success', ['alert', 'alert-success alert-dismissible fade show']); ?>
                <?= $this->flashMessenger()->render('info', ['alert', 'alert-info alert-dismissible fade show']); ?>
        </div>
        <div class="col-12">
            <div class="card">
                <!--div class="card-header"> 
                    <a class="btn btn-sm btn-primary float-right" href="< ?= $this->url('admin', ['action'=>'ajouter-prestation']); ?>">
                      Ajouter une nouvelle prestation
                    </a> 
                </div-->
                <div class="card-body">

                    <table id="prestation-datatable" width='100%' class="table dt-responsive nowrap">
                        <thead class="bg-secondary text-white">
                            
                            <tr>
                                <th>Envoyé par :</th>
                                <th>Email : </th>
                                <th> Objet du message : </th>
                                <th>Contenu du message : </th>
                                <th>Date de réception : </th>
                            </tr>
                        </thead>
                        <tbody class="bg-light">
                            <tr>
                                <td>
                                    <?= $msg->getNomUser();?>
                                </td>
                                <td>
                                    <?= $msg->getEmailUser();?>
                                </td>
                                <td>
                                    <?= $msg->getSujet();?>
                                </td>
                                <td>
                                    <?= $msg->getMessage();?>
                                </td>
                                <td>
                                    <?= $msg->getDateCreation();?>
                                </td>
                            </tr>  
                        </tbody>
                    </table>

                </div> <!-- end card body-->
            </div> <!-- end card -->
        </div><!-- end col-->
    </div>
    <!-- end row-->