<?php $this->HeadTitle('formations');?> 
<br><br>
<div class="row">
                <div class="col-lg-3 bg-transparent">
                    <h2></h2>
                </div>
    
                <div class="col-lg-6 bg-danger text-justify">
                       <h2 class="text-justify">Programme de formation</h2>
                </div>
                <div class="col-lg-3 bg-transparent">
                       <h2></h2>
                </div>
</div><br><br>
 <section class="ftco-intro ftco-no-pb img" style="background-image: url(img/bg_1.jpg);">
    	<div class="container">
    		<div class="row justify-content-center">
            <div class="col-lg-9 col-md-8 d-flex align-items-center heading-section heading-section-white ftco-animate">
              <marquee behavior="scroll"><h2 class="mb-3 mb-md-0 text-white">Vous obtenez toujours les meilleurs conseils!</h2></marquee>
              </div>
          <!--<div class="col-lg-3 col-md-4 ftco-animate">
          	<p class="mb-0"><a href="#" class="btn btn-white py-3 px-4">Request Quote</a></p>-->
            </div>
           </div>	
    	</div>
    </section> <!----end section banière---->
    
                 <!----section clients et partenaires---->

    <section class="ftco-section testimony-section">
                <div class="container">
                  <div class="row justify-content-center mb-5">
                    <div class="col-md-8 text-center heading-section ftco-animate">
                      <h2 class="mb-4 text-danger">Clients & Partenaires</h2>
                      <p>Ces structures on fait confiance à Gabriel & Raphaële Consulting</p>
                    </div>
                  </div>
                    <div class="row ftco-animate justify-content-center">
                      <div class="col-md-12">
                        <div class="carousel-testimony owl-carousel">
                          <div class="item">
                            <div class="testimony-wrap d-flex">
                              <div class="user-img" style="background-image: url(img/testyimg/dgemci.png)">
                              </div>
                              <div class="text pl-4">
                                    <span class="quote d-flex align-items-center justify-content-center">
                                  <i class="icon-quote-left"></i>
                                </span>
                                <p>Direction Générale des Ecoles Méthodistes.</p>
                                <p class="name font-weight-bold">DGEMCI</p>
                                <span class="position text-danger font-italic">Ils nous ont fait confiance!</span>
                              </div>
                            </div>
                          </div>
                          <div class="item">
                            <div class="testimony-wrap d-flex">
                              <div class="user-img" style="background-image: url(img/testyimg/meemci.png)">
                              </div>
                              <div class="text pl-4">
                                    <span class="quote d-flex align-items-center justify-content-center">
                                  <i class="icon-quote-left"></i>
                                </span>
                                <p>Mutuelle des Employes des Ecoles Méthodistes.</p>
                                <p class="name font-weight-bold">MEEM-CI</p>
                                <span class="position text-danger font-italic">Ils nous ont fait confiance!</span>
                              </div>
                            </div>
                          </div>
                          <div class="item">
                            <div class="testimony-wrap d-flex">
                              <div class="user-img" style="background-image: url(img/testyimg/maabs.png)">
                              </div>
                              <div class="text pl-4">
                                    <span class="quote d-flex align-items-center justify-content-center">
                                  <i class="icon-quote-left"></i>
                                </span>
                                <p>Mutuelle Sociale des agents de MaabSanté.</p>
                                <p class="name text font-weight-bold">MAABSanté</p>
                                <span class="position text-danger font-italic">Ils nous ont fait confiance!</span>
                              </div>
                            </div>
                          </div>
                          <div class="item">
                            <div class="testimony-wrap d-flex">
                              <div class="user-img" style="background-image: url(img/testyimg/musarti.png)">
                              </div>
                              <div class="text pl-4">
                                    <span class="quote d-flex align-items-center justify-content-center">
                                  <i class="icon-quote-left"></i>
                                </span>
                                <p>Mutuelle Sociale des Agents de la RTI.</p>
                                <p class="name font-weight-bold">MUSARTI</p>
                                <span class="position text-danger font-italic">Ils nous ont fait confiance!</span>
                              </div>
                            </div>
                          </div>
                          <div class="item">
                            <div class="testimony-wrap d-flex">
                              <div class="user-img" style="background-image: url(img/testyimg/mupartci.png)">
                              </div>
                              <div class="text pl-4">
                                    <span class="quote d-flex align-items-center justify-content-center">
                                  <i class="icon-quote-left"></i>
                                </span>
                                <p>Mutuelle du Personnel de l'ARTCI.</p>
                                <p class="name font-weight-bold">MUPARTCI</p>
                                <span class="position text-danger font-italic">Ils nous ont fait confiance!</span>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
    </section>  <!----section clients et partenaires---->
