
<?php $this->headTitle('nousconnaitre');?>

<section class="ftco-section">
			<div class="container">
				<div class="row d-flex">
					<div class="col-md-5 order-md-last wrap-about align-items-stretch">
						<div class="wrap-about-border">
							<div class="img" style="background-image: url(img/logogr/logogr1.jpg); border"></div>
							<div class="text">
								<h3></h3>
								<p></p>
								<!--<p><a href="#" class="btn btn-primary py-3 px-4">Contact us</a></p>-->
							</div>
						</div>
					</div>
					<div class="col-md-7 wrap-about pr-md-4 ftco-animate">
          	<h2 class="mb-4">Bienvenu à G&R Consulting</h2>
						<p>
						GABRIEL & RAPHAELE CONSULTGING dit G&R CONSULTING est une SARL au capital de 1 000 000 F CFA créée en octobre 2019 et issue des efforts, expériences et compétences combinés de jeunes cadres ivoiriens dans le but d’accompagner et d’aider les organisations sociales, les entreprises et les particuliers dans leur processus de développement durable, économique et social.
						</p>
					</div>
				</div>
			</div>
		</section>

		


